#!/usr/bin/env node
// Every string Undercut puts in front of other people lives here, so the
// copy is reviewed in one place. Rules (brand kit, "Approved copy"):
//   - Name + link, or real counts. Never a dollar claim and never the
//     headline number on a byline.
//   - Savings are always labelled "est." where they appear at all.
//   - Terminal output hyperlinks the name (see links.js); commit text can't,
//     so it carries the bare domain.

const SITE = "getundercut.sh";
const SITE_URL = "https://getundercut.sh";
const BADGE_URL = "https://getundercut.sh/badge.svg";
const CLAUDE_COAUTHOR = "Co-Authored-By: Claude <noreply@anthropic.com>";

// Trailer text Claude Code appends to commits. Keeps Claude Code's own
// co-author line: replacing it would drop Anthropic's attribution.
function commitTrailer() {
  return `${CLAUDE_COAUTHOR}\nRouted-With: Undercut (${SITE})`;
}

// Static PR footer (Claude Code's `attribution.pr` is a fixed string).
// Per-PR tier counts are added by the agent from its own routing
// narration, via the session context in session-start.js.
function prFooter({ badge = true } = {}) {
  const link = `[Undercut](${SITE_URL})`;
  if (!badge) return `Routed with ${link}`;
  return `[![routed with undercut](${BADGE_URL})](${SITE_URL})\n\nRouted with ${link}`;
}

function statsLine(cheapOrStandard, total) {
  return `${cheapOrStandard} of ${total} units ran cheap/standard`;
}

const TIPS = [
  "Tiers are assigned by a six-flag rubric; only verification failures escalate.",
  "Run `undercut share` for a copy-paste summary of the last 7 days.",
  "The receipt at the end of a session shows what actually ran, not a guess.",
  "Turn anything off with `undercut config <setting> off`; `branding off` turns off every byline and tip.",
  "Pro keeps the tier-to-model map current for you: getundercut.sh/pricing",
];

function tipFor(seed) {
  let h = 0;
  for (const ch of String(seed || "")) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return TIPS[h % TIPS.length];
}

// Appended to the spinner verbs Claude Code already has.
const SPINNER_VERBS = ["Tiering", "Verifying", "Escalating on evidence", "Undercutting"];

function generatedFileHeader(kind = "md") {
  const text = `Generated by Undercut (${SITE})`;
  return kind === "md" ? `<!-- ${text} -->` : `# ${text}`;
}

module.exports = {
  SITE,
  SITE_URL,
  BADGE_URL,
  CLAUDE_COAUTHOR,
  commitTrailer,
  prFooter,
  statsLine,
  TIPS,
  tipFor,
  SPINNER_VERBS,
  generatedFileHeader,
};
