#!/usr/bin/env node
// Holds the MCP server (site/api/mcp.js + site/api/_lib/mcp.js) and its
// discovery metadata to the data they actually serve.
//
//   1. Generated files are in sync:
//      - site/api/_lib/mcp-schemas.js: each tool's outputSchema is the
//        matching REST endpoint's 200 schema from site/openapi.json, with
//        every $ref inlined, so MCP and REST cannot describe the same data
//        differently.
//      - site/.well-known/mcp/server-card.json: the Server Card, built from
//        the server's own SERVER_INFO and SUPPORTED_VERSIONS.
//   2. tools/list is honest: exactly the expected read-only tools, each with
//      readOnlyHint true / destructiveHint false / openWorldHint false, an
//      object inputSchema, and an outputSchema.
//   3. Truth: every tool is called through the real protocol handler and its
//      structuredContent must deep-equal data.js (the same object the REST
//      handler returns) and validate against its outputSchema.
//   4. Discovery: the Server Card's shape (SEP-2127 draft), the AI Catalog
//      entry pointing at it, and the vercel.json rewrites all agree.
//
// Usage:
//   node scripts/validate-mcp.js --check   # exit 1 on any problem (read-only)
//   node scripts/validate-mcp.js --write   # regenerate the two generated files

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { isDeepStrictEqual } from 'node:util';
import path from 'node:path';
import { validateSchema, resolveRef, SPEC_PATH } from './validate-openapi.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SCHEMAS_PATH = path.join(repoRoot, 'site/api/_lib/mcp-schemas.js');
export const CARD_PATH = path.join(repoRoot, 'site/.well-known/mcp/server-card.json');
export const CATALOG_PATH = path.join(repoRoot, 'site/.well-known/ai-catalog.json');
export const VERCEL_PATH = path.join(repoRoot, 'site/vercel.json');

export const CARD_URL = 'https://getundercut.sh/mcp/server-card';
export const CARD_SCHEMA = 'https://static.modelcontextprotocol.io/schemas/v1/server-card.schema.json';
export const CARD_MEDIA_TYPE = 'application/mcp-server-card+json';

// tool name -> [OpenAPI component schema, data.js getter producing the same body]
export const TOOL_SOURCES = {
  list_clients: ['ClientList', (d) => ({ count: d.getClients().length, clients: d.getClients() })],
  get_client: ['Client', (d) => d.getClient('claude-code'), { slug: 'claude-code' }],
  get_segments: ['Segments', (d) => d.getSegments()],
  get_policy: ['Policy', (d) => d.getPolicy()],
  get_models: ['Models', (d) => d.getModels()],
  get_benchmark_results: ['Results', (d) => d.getResults()],
  get_pricing: ['Pricing', (d) => d.getPricing()],
  get_teams_availability: ['TeamsAvailability', (d) => d.getTeamsAvailability()],
};

/** Inlines every $ref in an OpenAPI schema node (the spec has no cycles). */
export function deref(spec, node) {
  if (Array.isArray(node)) return node.map((n) => deref(spec, n));
  if (!node || typeof node !== 'object') return node;
  if (node.$ref) {
    const { $ref, ...rest } = node;
    const target = resolveRef(spec, $ref);
    if (target === undefined) throw new Error(`unresolvable $ref ${$ref}`);
    return { ...deref(spec, target), ...deref(spec, rest) };
  }
  return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, deref(spec, v)]));
}

export function buildSchemasModule(spec) {
  const schemas = {};
  for (const [tool, [component]] of Object.entries(TOOL_SOURCES)) {
    schemas[tool] = { $schema: 'https://json-schema.org/draft/2020-12/schema', ...deref(spec, spec.components.schemas[component]) };
  }
  return [
    '// AUTO-GENERATED by scripts/validate-mcp.js --write from site/openapi.json.',
    '// Each MCP tool\'s outputSchema is its REST twin\'s documented 200 schema with',
    '// every $ref inlined. Do not edit by hand (CI runs validate-mcp.js --check).',
    `export default ${JSON.stringify(schemas, null, 2)};`,
    '',
  ].join('\n');
}

export function buildCard({ SERVER_INFO, SUPPORTED_VERSIONS, ENDPOINT }) {
  return {
    $schema: CARD_SCHEMA,
    name: SERVER_INFO.name,
    version: SERVER_INFO.version,
    title: SERVER_INFO.title,
    description: SERVER_INFO.description,
    websiteUrl: SERVER_INFO.websiteUrl,
    repository: { url: 'https://github.com/undercutsh/firstpass', source: 'github', subfolder: 'site/api' },
    icons: [{ src: 'https://getundercut.sh/android-chrome-512x512.png', mimeType: 'image/png', sizes: ['512x512'] }],
    remotes: [{ type: 'streamable-http', url: ENDPOINT, supportedProtocolVersions: SUPPORTED_VERSIONS }],
  };
}

// The SEP-2127 draft's required fields and constraints (ext-server-card
// schema.ts), checked by hand so CI needs no JSON Schema dependency.
export function checkCardShape(card) {
  const errors = [];
  if (card.$schema !== CARD_SCHEMA) errors.push(`server card $schema must be ${CARD_SCHEMA}`);
  if (!/^[a-zA-Z0-9.-]+\/[a-zA-Z0-9._-]+$/.test(card.name ?? '') || card.name.length > 200) errors.push('server card name must be reverse-DNS "namespace/name"');
  if (typeof card.version !== 'string' || !card.version || /[\^~><*x]/.test(card.version)) errors.push('server card version must be an exact version string');
  if (typeof card.description !== 'string' || card.description.length < 1 || card.description.length > 100) errors.push('server card description must be 1-100 characters');
  if (card.title !== undefined && (card.title.length < 1 || card.title.length > 100)) errors.push('server card title must be 1-100 characters');
  for (const r of card.remotes ?? []) {
    if (!['streamable-http', 'sse'].includes(r.type)) errors.push(`server card remote type ${r.type} is not streamable-http or sse`);
    if (!/^https?:\/\/\S+$/.test(r.url ?? '')) errors.push(`server card remote url ${r.url} is not an http(s) URL`);
  }
  for (const key of ['tools', 'resources', 'prompts']) if (key in card) errors.push(`server card must not enumerate ${key} (SEP-2127: primitives are listed at runtime)`);
  return errors;
}

export async function loadServer() {
  const mcp = await import(pathToFileURL(path.join(repoRoot, 'site/api/_lib/mcp.js')).href);
  const data = await import(pathToFileURL(path.join(repoRoot, 'site/api/_lib/data.js')).href);
  return { mcp, data };
}

const EXPECTED_HINTS = { readOnlyHint: true, destructiveHint: false, openWorldHint: false };

export async function check({ spec, card, catalog, vercel, schemasSource }) {
  const errors = [];
  const { mcp, data } = await loadServer();

  // 1. Generated files.
  if (schemasSource !== buildSchemasModule(spec)) errors.push('site/api/_lib/mcp-schemas.js is stale: run `node scripts/validate-mcp.js --write`');
  if (!isDeepStrictEqual(card, buildCard(mcp))) errors.push('site/.well-known/mcp/server-card.json is stale: run `node scripts/validate-mcp.js --write`');
  errors.push(...checkCardShape(card));

  // 2. tools/list.
  const names = mcp.TOOLS.map((t) => t.name);
  if (!isDeepStrictEqual(names, Object.keys(TOOL_SOURCES))) errors.push(`tools/list names ${names.join(',')} != expected ${Object.keys(TOOL_SOURCES).join(',')}`);
  for (const t of mcp.TOOLS) {
    for (const [k, v] of Object.entries(EXPECTED_HINTS)) if (t.annotations?.[k] !== v) errors.push(`${t.name}: annotations.${k} must be ${v}`);
    if (t.inputSchema?.type !== 'object') errors.push(`${t.name}: inputSchema.type must be "object"`);
    if (t.outputSchema?.type !== 'object') errors.push(`${t.name}: outputSchema.type must be "object"`);
    if (!t.description) errors.push(`${t.name}: missing description`);
  }

  // 3. Every tool through the real handler, both eras.
  const eras = {
    legacy: { headers: { 'mcp-protocol-version': '2025-11-25' }, meta: undefined },
    modern: { headers: { 'mcp-protocol-version': '2026-07-28', 'mcp-method': 'tools/call' }, meta: { 'io.modelcontextprotocol/protocolVersion': '2026-07-28', 'io.modelcontextprotocol/clientCapabilities': {} } },
  };
  for (const [tool, [, getter, args = {}]] of Object.entries(TOOL_SOURCES)) {
    if (!names.includes(tool)) continue;
    const expected = getter(data);
    for (const [era, { headers, meta }] of Object.entries(eras)) {
      const params = { name: tool, arguments: args, ...(meta ? { _meta: meta } : {}) };
      const { status, body } = mcp.handleMessage({ jsonrpc: '2.0', id: 1, method: 'tools/call', params }, { ...headers, ...(meta ? { 'mcp-name': tool } : {}) });
      const res = body?.result;
      if (status !== 200 || !res || res.isError) { errors.push(`${tool} (${era}): call failed: ${JSON.stringify(body).slice(0, 200)}`); continue; }
      if (!isDeepStrictEqual(res.structuredContent, expected)) errors.push(`${tool} (${era}): structuredContent differs from data.js`);
      if (res.content?.[0]?.type !== 'text' || !isDeepStrictEqual(JSON.parse(res.content[0].text), expected)) errors.push(`${tool} (${era}): text content is not the JSON of structuredContent`);
      const tdef = mcp.TOOLS.find((t) => t.name === tool);
      errors.push(...validateSchema({}, tdef.outputSchema, res.structuredContent).map((e) => `${tool} (${era}): outputSchema: ${e}`));
    }
  }

  // 4. Discovery metadata.
  const discover = mcp.handleMessage({ jsonrpc: '2.0', id: 1, method: 'server/discover', params: { _meta: eras.modern.meta } }, { ...eras.modern.headers, 'mcp-method': 'server/discover' }).body?.result;
  if (!isDeepStrictEqual(discover?.supportedVersions, card.remotes?.[0]?.supportedProtocolVersions)) errors.push('server/discover supportedVersions != server card remotes[0].supportedProtocolVersions');
  const entry = (catalog.entries ?? []).find((e) => e.type === CARD_MEDIA_TYPE);
  if (!entry) errors.push(`ai-catalog.json has no ${CARD_MEDIA_TYPE} entry`);
  else {
    if (entry.url !== CARD_URL) errors.push(`ai-catalog.json MCP entry url must be ${CARD_URL}`);
    if (!entry.trustManifest?.identity?.url) errors.push('ai-catalog.json MCP entry needs a trustManifest like the other entries');
    for (const name of names) if (!entry.description?.includes(name)) errors.push(`ai-catalog.json MCP entry description does not mention tool ${name}`);
  }
  if (/no mcp server/i.test(catalog.notes ?? '')) errors.push('ai-catalog.json notes still says no MCP server exists');
  const rewrites = vercel.rewrites ?? [];
  const dest = (src) => rewrites.find((r) => r.source === src)?.destination;
  if (dest('/mcp') !== '/api/mcp') errors.push('vercel.json must rewrite /mcp to /api/mcp');
  if (dest('/mcp/server-card') !== '/.well-known/mcp/server-card.json') errors.push('vercel.json must rewrite /mcp/server-card to /.well-known/mcp/server-card.json');
  return errors;
}

function readAll() {
  const json = (p) => JSON.parse(readFileSync(p, 'utf8'));
  let card = {};
  try { card = json(CARD_PATH); } catch { /* reported as stale */ }
  return {
    spec: json(SPEC_PATH),
    card,
    catalog: json(CATALOG_PATH),
    vercel: json(VERCEL_PATH),
    schemasSource: readFileSync(SCHEMAS_PATH, 'utf8'),
  };
}

async function main() {
  const mode = process.argv[2];
  if (mode === '--write') {
    const spec = JSON.parse(readFileSync(SPEC_PATH, 'utf8'));
    writeFileSync(SCHEMAS_PATH, buildSchemasModule(spec));
    const { mcp } = await loadServer();
    mkdirSync(path.dirname(CARD_PATH), { recursive: true });
    writeFileSync(CARD_PATH, `${JSON.stringify(buildCard(mcp), null, 2)}\n`);
    console.log('Wrote site/api/_lib/mcp-schemas.js and site/.well-known/mcp/server-card.json');
    return;
  }
  if (mode !== '--check') {
    console.error('usage: node scripts/validate-mcp.js --check | --write');
    process.exit(2);
  }
  const errors = await check(readAll());
  if (errors.length) {
    console.error(`MCP server does not match its data or discovery metadata (${errors.length} issue${errors.length === 1 ? '' : 's'}):\n`);
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }
  console.log(`MCP server is consistent: ${Object.keys(TOOL_SOURCES).length} read-only tools, each returning data.js's data and matching its outputSchema; server card, AI Catalog entry and vercel.json rewrites agree.`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error(`validate-mcp.js: ${e.message}`);
    process.exit(1);
  });
}
